from __future__ import annotations

from product_mapping.types import ProductCandidate


_BUILTIN_CATALOG: tuple[ProductCandidate, ...] = (
    ProductCandidate(
        product_id="cn_equity_csi300_etf",
        product_name="沪深300ETF",
        asset_bucket="equity_cn",
        product_family="broad_market_etf",
        wrapper_type="etf",
        provider_source="builtin_cn_public_funds",
        provider_symbol="510300",
        market="CN",
        liquidity_tier="high",
        fee_tier="low",
        tracking_quality="high",
        valuation_percentile=0.34,
        core_or_satellite="core",
        tags=["core", "broad_market"],
        style_tags=["broad_market", "large_cap"],
        risk_labels=["权益波动"],
        notes=["A 股核心宽基，适合作为权益核心仓。"],
    ),
    ProductCandidate(
        product_id="cn_equity_dividend_etf",
        product_name="红利ETF",
        asset_bucket="equity_cn",
        product_family="dividend_etf",
        wrapper_type="etf",
        provider_source="builtin_cn_public_funds",
        provider_symbol="510880",
        market="CN",
        liquidity_tier="high",
        fee_tier="low",
        tracking_quality="high",
        valuation_percentile=0.29,
        core_or_satellite="core",
        tags=["equity", "dividend"],
        style_tags=["dividend", "value"],
        risk_labels=["权益波动"],
        notes=["权益核心仓的红利/价值风格补充。"],
    ),
    ProductCandidate(
        product_id="cn_equity_lowvol_etf",
        product_name="低波ETF",
        asset_bucket="equity_cn",
        product_family="low_volatility_etf",
        wrapper_type="etf",
        provider_source="builtin_cn_public_funds",
        provider_symbol="512890",
        market="CN",
        liquidity_tier="medium",
        fee_tier="low",
        tracking_quality="medium",
        valuation_percentile=0.31,
        core_or_satellite="core",
        tags=["equity", "low_vol"],
        style_tags=["low_vol", "defensive_equity"],
        risk_labels=["权益波动"],
        notes=["降低权益桶波动的低波风格补充。"],
    ),
    ProductCandidate(
        product_id="cn_equity_csi300_index_fund",
        product_name="沪深300指数基金",
        asset_bucket="equity_cn",
        product_family="broad_market_index_fund",
        wrapper_type="fund",
        provider_source="builtin_cn_public_funds",
        provider_symbol="161207",
        market="CN",
        liquidity_tier="medium",
        fee_tier="medium",
        tracking_quality="medium",
        valuation_percentile=0.34,
        core_or_satellite="core",
        tags=["equity", "fund"],
        style_tags=["broad_market", "index_fund"],
        risk_labels=["权益波动"],
        notes=["场外指数基金，用于与 ETF 包装层对照。"],
    ),
    ProductCandidate(
        product_id="cn_stock_moutai",
        product_name="贵州茅台",
        asset_bucket="equity_cn",
        product_family="china_a_single_stock",
        wrapper_type="single_stock",
        provider_source="builtin_cn_equities",
        provider_symbol="600519",
        market="CN",
        liquidity_tier="high",
        fee_tier="low",
        tracking_quality="low",
        valuation_percentile=0.82,
        core_or_satellite="satellite",
        tags=["single_stock", "consumer"],
        style_tags=["single_stock", "consumer"],
        risk_labels=["个股集中风险", "权益波动"],
        notes=["仅在允许个股时作为卫星备选，不得默认替代指数核心。"],
    ),
    ProductCandidate(
        product_id="cn_bond_gov_etf",
        product_name="国债ETF",
        asset_bucket="bond_cn",
        product_family="gov_bond_etf",
        wrapper_type="etf",
        provider_source="builtin_cn_public_funds",
        provider_symbol="511010",
        market="CN",
        liquidity_tier="high",
        fee_tier="low",
        tracking_quality="high",
        valuation_percentile=0.45,
        core_or_satellite="defense",
        tags=["defense", "gov_bond"],
        style_tags=["gov_bond", "mid_duration"],
        risk_labels=["利率波动"],
        notes=["债券主仓，兼顾流动性与透明度。"],
    ),
    ProductCandidate(
        product_id="cn_bond_policy_bank_etf",
        product_name="政金债ETF",
        asset_bucket="bond_cn",
        product_family="policy_bank_bond_etf",
        wrapper_type="etf",
        provider_source="builtin_cn_public_funds",
        provider_symbol="511520",
        market="CN",
        liquidity_tier="medium",
        fee_tier="low",
        tracking_quality="high",
        valuation_percentile=0.41,
        core_or_satellite="defense",
        tags=["defense", "policy_bank"],
        style_tags=["policy_bank", "mid_duration"],
        risk_labels=["利率波动"],
        notes=["债券防守仓的政金债补充。"],
    ),
    ProductCandidate(
        product_id="cn_bond_short_bond_fund",
        product_name="中短债基金",
        asset_bucket="bond_cn",
        product_family="short_bond_fund",
        wrapper_type="fund",
        provider_source="builtin_cn_public_funds",
        provider_symbol="006007",
        market="CN",
        liquidity_tier="medium",
        fee_tier="low",
        tracking_quality="medium",
        valuation_percentile=0.40,
        core_or_satellite="defense",
        tags=["defense", "short_duration"],
        style_tags=["short_duration", "fund"],
        risk_labels=["净值波动"],
        notes=["用于压缩久期和留出流动性机动。"],
    ),
    ProductCandidate(
        product_id="cn_bond_pure_bond_fund",
        product_name="纯债基金",
        asset_bucket="bond_cn",
        product_family="pure_bond_fund",
        wrapper_type="fund",
        provider_source="builtin_cn_public_funds",
        provider_symbol="000402",
        market="CN",
        liquidity_tier="medium",
        fee_tier="medium",
        tracking_quality="medium",
        valuation_percentile=0.44,
        core_or_satellite="defense",
        tags=["defense", "fund"],
        style_tags=["credit_bond", "fund"],
        risk_labels=["信用利差", "净值波动"],
        notes=["债券桶补充，体现不同封装与信用敞口。"],
    ),
    ProductCandidate(
        product_id="cn_gold_etf",
        product_name="黄金ETF",
        asset_bucket="gold",
        product_family="gold_etf",
        wrapper_type="etf",
        provider_source="builtin_cn_public_funds",
        provider_symbol="518880",
        market="CN",
        liquidity_tier="high",
        fee_tier="low",
        tracking_quality="high",
        valuation_percentile=0.48,
        core_or_satellite="defense",
        tags=["gold", "inflation_hedge"],
        style_tags=["gold", "etf"],
        risk_labels=["商品波动"],
        notes=["黄金桶主推产品。"],
    ),
    ProductCandidate(
        product_id="cn_gold_linked_fund",
        product_name="黄金联接基金",
        asset_bucket="gold",
        product_family="gold_linked_fund",
        wrapper_type="fund",
        provider_source="builtin_cn_public_funds",
        provider_symbol="000218",
        market="CN",
        liquidity_tier="medium",
        fee_tier="medium",
        tracking_quality="medium",
        valuation_percentile=0.48,
        core_or_satellite="defense",
        tags=["gold", "fund"],
        style_tags=["gold", "linked_fund"],
        risk_labels=["商品波动"],
        notes=["黄金场外包装，对比 ETF 执行差异。"],
    ),
    ProductCandidate(
        product_id="cn_gold_accumulation",
        product_name="积存金",
        asset_bucket="gold",
        product_family="gold_savings",
        wrapper_type="savings",
        provider_source="builtin_cn_banks",
        provider_symbol="gold_accumulation",
        market="CN",
        liquidity_tier="medium",
        fee_tier="medium",
        tracking_quality="medium",
        valuation_percentile=0.48,
        core_or_satellite="defense",
        tags=["gold", "savings"],
        style_tags=["gold", "savings"],
        risk_labels=["商品波动", "点差"],
        notes=["适合长期定投型黄金配置。"],
    ),
    ProductCandidate(
        product_id="cn_cash_money_fund",
        product_name="货币基金",
        asset_bucket="cash_liquidity",
        product_family="money_market_fund",
        wrapper_type="cash_mgmt",
        provider_source="builtin_cn_public_funds",
        provider_symbol="000638",
        market="CN",
        liquidity_tier="high",
        fee_tier="low",
        tracking_quality="high",
        valuation_percentile=0.50,
        core_or_satellite="cash",
        tags=["cash", "liquidity"],
        style_tags=["money_market"],
        risk_labels=["低收益"],
        notes=["现金管理仓位的第一选择。"],
    ),
    ProductCandidate(
        product_id="cn_cash_short_bond_fund",
        product_name="短债基金",
        asset_bucket="cash_liquidity",
        product_family="short_bond_fund",
        wrapper_type="fund",
        provider_source="builtin_cn_public_funds",
        provider_symbol="000128",
        market="CN",
        liquidity_tier="medium",
        fee_tier="low",
        tracking_quality="medium",
        valuation_percentile=0.47,
        core_or_satellite="cash",
        tags=["cash", "short_duration"],
        style_tags=["short_duration", "fund"],
        risk_labels=["净值小幅波动"],
        notes=["现金仓的轻微收益增强。"],
    ),
    ProductCandidate(
        product_id="cn_cash_broker_mgmt",
        product_name="券商现金管理",
        asset_bucket="cash_liquidity",
        product_family="broker_cash_management",
        wrapper_type="cash_mgmt",
        provider_source="builtin_cn_brokers",
        provider_symbol="broker_cash",
        market="CN",
        liquidity_tier="high",
        fee_tier="low",
        tracking_quality="high",
        valuation_percentile=0.50,
        core_or_satellite="cash",
        tags=["cash", "broker"],
        style_tags=["cash_management"],
        risk_labels=["低收益"],
        notes=["承接待买现金与执行缓冲。"],
    ),
    ProductCandidate(
        product_id="cn_satellite_chip_etf",
        product_name="芯片ETF",
        asset_bucket="satellite",
        product_family="technology_theme_etf",
        wrapper_type="etf",
        provider_source="builtin_cn_public_funds",
        provider_symbol="159995",
        market="CN",
        liquidity_tier="high",
        fee_tier="medium",
        tracking_quality="medium",
        valuation_percentile=0.58,
        policy_news_score=0.82,
        core_or_satellite="satellite",
        tags=["satellite", "technology"],
        style_tags=["technology", "chip"],
        risk_labels=["主题波动", "权益波动"],
        notes=["政策/景气驱动的科技卫星仓。"],
    ),
    ProductCandidate(
        product_id="cn_satellite_robotics_etf",
        product_name="机器人ETF",
        asset_bucket="satellite",
        product_family="robotics_theme_etf",
        wrapper_type="etf",
        provider_source="builtin_cn_public_funds",
        provider_symbol="562500",
        market="CN",
        liquidity_tier="medium",
        fee_tier="medium",
        tracking_quality="medium",
        valuation_percentile=0.46,
        policy_news_score=0.76,
        core_or_satellite="satellite",
        tags=["satellite", "manufacturing"],
        style_tags=["technology", "robotics"],
        risk_labels=["主题波动", "权益波动"],
        notes=["主题卫星仓，适合政策产业链增强。"],
    ),
    ProductCandidate(
        product_id="cn_satellite_hsi_tech_qdii",
        product_name="恒生科技QDII",
        asset_bucket="satellite",
        product_family="hongkong_tech_qdii",
        wrapper_type="fund",
        provider_source="builtin_cn_public_funds",
        provider_symbol="012349",
        market="HK",
        liquidity_tier="medium",
        fee_tier="medium",
        tracking_quality="medium",
        valuation_percentile=0.39,
        policy_news_score=0.66,
        core_or_satellite="satellite",
        tags=["satellite", "qdii"],
        style_tags=["technology", "qdii", "hongkong"],
        risk_labels=["主题波动", "汇率波动"],
        notes=["港股科技卫星仓。"],
    ),
    ProductCandidate(
        product_id="cn_satellite_sp500_qdii",
        product_name="标普500QDII",
        asset_bucket="satellite",
        product_family="us_broad_qdii",
        wrapper_type="fund",
        provider_source="builtin_cn_public_funds",
        provider_symbol="161125",
        market="US",
        liquidity_tier="medium",
        fee_tier="medium",
        tracking_quality="high",
        valuation_percentile=0.52,
        policy_news_score=0.41,
        core_or_satellite="satellite",
        tags=["satellite", "qdii"],
        style_tags=["us_broad_market", "qdii"],
        risk_labels=["海外权益波动", "汇率波动"],
        notes=["全球分散化卫星候选。"],
    ),
    ProductCandidate(
        product_id="cn_satellite_energy_etf",
        product_name="能源ETF",
        asset_bucket="satellite",
        product_family="energy_theme_etf",
        wrapper_type="etf",
        provider_source="builtin_cn_public_funds",
        provider_symbol="159930",
        market="CN",
        liquidity_tier="medium",
        fee_tier="medium",
        tracking_quality="medium",
        valuation_percentile=0.27,
        policy_news_score=0.58,
        core_or_satellite="satellite",
        tags=["satellite", "energy"],
        style_tags=["energy", "resources"],
        risk_labels=["主题波动", "商品周期波动"],
        notes=["非科技主题的资源卫星仓。"],
    ),
)


def load_builtin_catalog() -> list[ProductCandidate]:
    return list(_BUILTIN_CATALOG)
