from __future__ import annotations

from product_mapping.types import ProductCandidate


_BUILTIN_CATALOG: tuple[ProductCandidate, ...] = (
    ProductCandidate(
        product_id="cn_equity_csi300_etf",
        product_name="沪深300ETF",
        asset_bucket="equity_cn",
        product_family="broad_market_etf",
        wrapper_type="etf",
        provider_source="builtin_cn_public_funds",
        provider_symbol="510300",
        liquidity_tier="high",
        fee_tier="low",
        tags=["core", "broad_market"],
        risk_labels=["权益波动"],
        notes=["宽基权益敞口，适合作为 A 股核心仓位。"],
    ),
    ProductCandidate(
        product_id="cn_equity_dividend_etf",
        product_name="红利ETF",
        asset_bucket="equity_cn",
        product_family="dividend_etf",
        wrapper_type="etf",
        provider_source="builtin_cn_public_funds",
        provider_symbol="510880",
        liquidity_tier="high",
        fee_tier="low",
        tags=["equity", "dividend"],
        risk_labels=["权益波动"],
        notes=["作为权益桶替代品，便于展示不同风格但不改写桶结论。"],
    ),
    ProductCandidate(
        product_id="cn_bond_gov_etf",
        product_name="国债ETF",
        asset_bucket="bond_cn",
        product_family="gov_bond_etf",
        wrapper_type="etf",
        provider_source="builtin_cn_public_funds",
        provider_symbol="511010",
        liquidity_tier="high",
        fee_tier="low",
        tags=["defense", "liquidity"],
        risk_labels=["利率波动"],
        notes=["优先作为防守桶与流动性缓冲的低复杂度实现。"],
    ),
    ProductCandidate(
        product_id="cn_bond_pure_bond_fund",
        product_name="纯债基金",
        asset_bucket="bond_cn",
        product_family="pure_bond_fund",
        wrapper_type="fund",
        provider_source="builtin_cn_public_funds",
        provider_symbol="000402",
        liquidity_tier="medium",
        fee_tier="medium",
        tags=["defense", "fund"],
        risk_labels=["信用利差", "净值波动"],
        notes=["作为债券桶替代品，适合解释‘同桶不同封装’。"],
    ),
    ProductCandidate(
        product_id="cn_gold_etf",
        product_name="黄金ETF",
        asset_bucket="gold",
        product_family="gold_etf",
        wrapper_type="etf",
        provider_source="builtin_cn_public_funds",
        provider_symbol="518880",
        liquidity_tier="high",
        fee_tier="low",
        tags=["defense", "inflation_hedge"],
        risk_labels=["商品波动"],
        notes=["作为黄金桶主推产品，流动性和可解释性更强。"],
    ),
    ProductCandidate(
        product_id="cn_gold_linked_fund",
        product_name="黄金联接基金",
        asset_bucket="gold",
        product_family="gold_linked_fund",
        wrapper_type="fund",
        provider_source="builtin_cn_public_funds",
        provider_symbol="000218",
        liquidity_tier="medium",
        fee_tier="medium",
        tags=["gold", "fund"],
        risk_labels=["商品波动"],
        notes=["保留为黄金桶替代品，便于前台解释产品封装差异。"],
    ),
    ProductCandidate(
        product_id="cn_cash_money_fund",
        product_name="货币基金",
        asset_bucket="cash_liquidity",
        product_family="money_market_fund",
        wrapper_type="cash_mgmt",
        provider_source="builtin_cn_public_funds",
        provider_symbol="000638",
        liquidity_tier="high",
        fee_tier="low",
        tags=["cash", "liquidity"],
        risk_labels=["低收益"],
        notes=["作为现金/流动性桶主推选项，用于承接未投资或低波动需求。"],
    ),
    ProductCandidate(
        product_id="cn_cash_short_bond_fund",
        product_name="短债基金",
        asset_bucket="cash_liquidity",
        product_family="short_bond_fund",
        wrapper_type="fund",
        provider_source="builtin_cn_public_funds",
        provider_symbol="000128",
        liquidity_tier="medium",
        fee_tier="low",
        tags=["cash", "short_duration"],
        risk_labels=["净值小幅波动"],
        notes=["作为现金/流动性桶替代品，保留更高收益但略低流动性的选择。"],
    ),
)


def load_builtin_catalog() -> list[ProductCandidate]:
    return list(_BUILTIN_CATALOG)
