"""Shared utility namespace for demo flows and reusable local scenarios."""

from .demo_flow import (
    build_demo_allocation_input,
    build_demo_behavior_raw,
    build_demo_constraint_raw,
    build_demo_goal_raw,
    build_demo_goal_solver_input,
    build_demo_live_portfolio,
    build_demo_market_raw,
    run_demo_journey,
    run_demo_monthly_replay_override,
    run_demo_onboarding,
    run_demo_provenance_bypass,
    run_demo_quarterly_review,
    serialize_demo_journey,
)
from .demo_scenarios import (
    CANONICAL_DEMO_SCENARIOS,
    DEMO_SCENARIO_ALIASES,
    DEMO_SCENARIOS,
    build_demo_report,
    normalize_demo_scenario_name,
    render_demo_report,
    run_demo_lifecycle,
    run_demo_monthly_followup,
    run_demo_provenance_blocked,
    run_demo_provenance_relaxed,
    summarize_demo_lifecycle,
)

__all__ = [
    "CANONICAL_DEMO_SCENARIOS",
    "DEMO_SCENARIO_ALIASES",
    "DEMO_SCENARIOS",
    "build_demo_allocation_input",
    "build_demo_behavior_raw",
    "build_demo_constraint_raw",
    "build_demo_goal_raw",
    "build_demo_goal_solver_input",
    "build_demo_live_portfolio",
    "build_demo_market_raw",
    "build_demo_report",
    "normalize_demo_scenario_name",
    "render_demo_report",
    "run_demo_journey",
    "run_demo_lifecycle",
    "run_demo_monthly_followup",
    "run_demo_monthly_replay_override",
    "run_demo_onboarding",
    "run_demo_provenance_blocked",
    "run_demo_provenance_bypass",
    "run_demo_provenance_relaxed",
    "run_demo_quarterly_review",
    "serialize_demo_journey",
    "summarize_demo_lifecycle",
]
